import { IEvent } from "@/interfaces/interfaces";

export const categories = [
	"All",
	"Concert",
	"Conference",
	"Workshop",
	"Festival",
	"Sports",
];

export const locations = [
	"Grand Arena, Downtown",
	"City Convention Center",
	"Community Hall",
	"Tech Hub",
	"River Side Park",
];

export const events: IEvent[] = [
	{
		id: "1",
		title: "Summer Music Festival 2025",
		description: "Experience the biggest music festival of the year with top artists from around the world.",
		date: "Jul 15, 2025",
		time: "18:00",
		location: "Grand Arena, Downtown",
		price: 99.99,
		image: "/ekko.png",
		category: "Festival",
		isFeatured: true,
	},
	{
		id: "2",
		title: "Tech Innovators Conference",
		description: "Join industry leaders to discuss the future of technology and innovation.",
		date: "Aug 20, 2025",
		time: "09:00",
		location: "City Convention Center",
		price: 299.00,
		image: "/ekko.png",
		category: "Conference",
	},
	{
		id: "3",
		title: "Jazz Night at the Park",
		description: "A relaxing evening of smooth jazz and good vibes under the stars.",
		date: "Sep 10, 2025",
		time: "19:30",
		location: "River Side Park",
		price: 45.50,
		image: "/ekko.png",
		category: "Concert",
	},
	{
		id: "4",
		title: "Digital Marketing Workshop",
		description: "Learn the latest strategies in digital marketing from experts.",
		date: "Oct 05, 2025",
		time: "10:00",
		location: "Tech Hub",
		price: 150.00,
		image: "/ekko.png",
		category: "Workshop",
	},
	{
		id: "5",
		title: "City Marathon 2025",
		description: "Run through the city's most scenic routes in our annual marathon.",
		date: "Nov 12, 2025",
		time: "06:00",
		location: "Downtown",
		price: 60.00,
		image: "/ekko.png",
		category: "Sports",
		isFeatured: true,
	},
	{
		id: "6",
		title: "Winter Classical Gala",
		description: "An elegant night of classical masterpieces performed by the City Orchestra.",
		date: "Dec 24, 2025",
		time: "20:00",
		location: "Grand Arena, Downtown",
		price: 120.00,
		image: "/ekko.png",
		category: "Concert",
	},
	{
		id: "7",
		title: "Startup Pitch Night",
		description: "Watch local startups pitch their ideas to investors.",
		date: "Jan 15, 2026",
		time: "18:00",
		location: "Tech Hub",
		price: 25.00,
		image: "/ekko.png",
		category: "Conference",
	},
	{
		id: "8",
		title: "Pottery Workshop",
		description: "Hands-on pottery class for beginners.",
		date: "Feb 14, 2026",
		time: "14:00",
		location: "Community Hall",
		price: 80.00,
		image: "/ekko.png",
		category: "Workshop",
	},
	{
		id: "9",
		title: "Pottery Workshop 2",
		description: "Hands-on pottery class for beginners.",
		date: "Feb 14, 2026",
		time: "14:00",
		location: "Community Hall",
		price: 80.00,
		image: "/ekko.png",
		category: "Workshop",
	},
	{
		id: "10",
		title: "Pottery Workshop 3",
		description: "Watch local startups pitch their ideas to investors.",
		date: "Dec 24, 2025",
		time: "14:00",
		location: "Tech Hub",
		price: 10000.00,
		image: "/ekko.png",
		category: "Sports",
	},
];
